site:
  name: template

  locales: [en, fr, de]

  seo_title: template
  meta_keywords: "some meta keywords"
  meta_description: "some meta description"

  pages:
    - "index": # page path (the template can edited here app/views/pages/index.liquid)
        title: "Home page"
        published: true
    - "404":
        title: "Page not found"
        published: true